#!/bin/bash -e

# Firmware version stamp (written by CI from the git tag)
[ -f "${STAGE_DIR}/files/opensonix-release" ] && \
    install -m 644 "${STAGE_DIR}/files/opensonix-release" "${ROOTFS_DIR}/etc/opensonix-release"

install -d "${ROOTFS_DIR}/etc/baresip"
install -m 664 "${STAGE_DIR}/files/baresip-config/config"   "${ROOTFS_DIR}/etc/baresip/config"
install -m 664 "${STAGE_DIR}/files/baresip-config/accounts" "${ROOTFS_DIR}/etc/baresip/accounts"
install -d "${ROOTFS_DIR}/etc/alsa/conf.d"
cat > "${ROOTFS_DIR}/etc/alsa/conf.d/99-opensonix-meter.conf" << 'ALSAMETEREOF'
# Generated by OpenSonix. ALSA software volumes and taps for UI audio levels.
# The web UI rewrites this file with the selected devices; "default" keeps
# baresip bootable before the first UI-side configuration apply.
pcm.opensonix_volume_play {
  type softvol
  slave.pcm "default"
  control {
    name "OpenSonix Playback"
    card "0"
  }
  min_dB -60.0
  max_dB 0.0
  resolution 101
}

pcm.opensonix_volume_cap {
  type softvol
  slave.pcm "default"
  control {
    name "OpenSonix Capture"
    card "0"
  }
  min_dB -60.0
  max_dB 0.0
  resolution 101
}

pcm.opensonix_meter_play {
  type file
  slave.pcm "opensonix_volume_play"
  file "|/usr/bin/node /opt/opensonix/ui/server/audio-meter.js rx %f %c"
  format raw
}

pcm.opensonix_meter_cap {
  type file
  slave.pcm "opensonix_volume_cap"
  file "|/usr/bin/node /opt/opensonix/ui/server/audio-meter.js tx %f %c"
  format raw
}
ALSAMETEREOF

install -d -m 750 "${ROOTFS_DIR}/var/lib/opensonix"

on_chroot << 'EOF'
chown root:opensonix /etc/baresip /etc/baresip/config /etc/baresip/accounts
chmod 775 /etc/baresip
chmod 664 /etc/baresip/config /etc/baresip/accounts
chown root:opensonix /etc/alsa/conf.d/99-opensonix-meter.conf
chmod 664 /etc/alsa/conf.d/99-opensonix-meter.conf

chown -R opensonix:opensonix /opt/opensonix
chown    opensonix:opensonix /var/lib/opensonix
EOF

# ── Sudo (NOPASSWD — opensonix-ui service runs systemctl, timedatectl, etc.) ──
echo "opensonix ALL=(ALL) NOPASSWD: ALL" \
    > "${ROOTFS_DIR}/etc/sudoers.d/010_opensonix-nopasswd"
chmod 440 "${ROOTFS_DIR}/etc/sudoers.d/010_opensonix-nopasswd"

# ── Network (systemd-networkd) ────────────────────────────────────────────────
mkdir -p "${ROOTFS_DIR}/etc/systemd/network"
cat > "${ROOTFS_DIR}/etc/systemd/network/10-eth0.network" << 'NETEOF'
[Match]
Name=eth0

[Network]
DHCP=yes
NETEOF
# Note: resolv.conf is intentionally NOT set to a symlink here.
# Creating a dangling symlink during build breaks DNS in subsequent pi-gen
# stages (export-image). Pi-gen copies the host resolv.conf into the image;
# the host runner uses 127.0.0.53, which maps to our systemd-resolved on
# the Pi at runtime.

# ── NTP (chrony) ──────────────────────────────────────────────────────────────
# Install default config with European NTP pool servers.
cat > "${ROOTFS_DIR}/etc/chrony/chrony.conf" << 'CHRONYEOF'
# Generated by OpenSonix — managed via web UI
server 0.europe.pool.ntp.org iburst
server 1.europe.pool.ntp.org iburst

makestep 1.0 3
driftfile /var/lib/chrony/chrony.drift
rtcsync
CHRONYEOF

# ── Audio HATs ────────────────────────────────────────────────────────────────
# OpenSonix targets Raspberry Pi audio codecs. Enable the common HiFiBerry
# DAC+ ADC overlay by default so cards without HAT EEPROM are available to ALSA.
BOOT_CONFIG="${ROOTFS_DIR}/boot/firmware/config.txt"
[ -f "${BOOT_CONFIG}" ] || BOOT_CONFIG="${ROOTFS_DIR}/boot/config.txt"
if [ -f "${BOOT_CONFIG}" ]; then
    sed -i 's/^dtparam=audio=on/#dtparam=audio=on/' "${BOOT_CONFIG}"
    cat >> "${BOOT_CONFIG}" << 'AUDIOHATEOF'

# OpenSonix audio HAT support
dtparam=i2s=on
dtparam=audio=off
dtoverlay=hifiberry-dacplusadc
AUDIOHATEOF
fi

mkdir -p "${ROOTFS_DIR}/etc/alsa/conf.d"
cat > "${ROOTFS_DIR}/etc/alsa/conf.d/99-opensonix-hifiberry.conf" << 'ALSAHATEOF'
# OpenSonix HiFiBerry DAC+ ADC full-duplex PCMs.
# The HAT exposes S32_LE through dmix/dsnoop; the outer plug layer lets
# baresip keep using its S16_LE audio pipeline while ALSA performs conversion.
pcm.opensonix_hifiberry_play {
  type plug
  slave.pcm {
    type dmix
    ipc_key 7060001
    slave {
      pcm "hw:CARD=sndrpihifiberry,DEV=0"
      format S32_LE
      rate 48000
      channels 2
      period_time 0
      period_size 1024
      buffer_size 8192
    }
  }
}

pcm.opensonix_hifiberry_cap {
  type plug
  slave.pcm {
    type dsnoop
    ipc_key 7060002
    slave {
      pcm "hw:CARD=sndrpihifiberry,DEV=0"
      format S32_LE
      rate 48000
      channels 2
      period_time 0
      period_size 1024
      buffer_size 8192
    }
  }
}
ALSAHATEOF

# ── Console keyboard ──────────────────────────────────────────────────────────
# OpenSonix intentionally skips pi-gen stage2, where Raspberry Pi OS normally
# installs and configures console-setup/keyboard-configuration.
KEYMAP="${KEYBOARD_KEYMAP:-fr}"
cat > "${ROOTFS_DIR}/etc/default/keyboard" << KEYBOARDEOF
XKBMODEL="pc105"
XKBLAYOUT="${KEYMAP}"
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"
KEYBOARDEOF

on_chroot << 'EOF'
DEBIAN_FRONTEND=noninteractive dpkg-reconfigure keyboard-configuration console-setup
setupcon --force --save-only -v

# Root should never be a login account on OpenSonix images. Administration is
# performed through the opensonix user and sudo.
passwd -l root || true

EOF

# ── SSH hardening ─────────────────────────────────────────────────────────────
# Keep SSH password auth disabled until the web first-login flow has set a
# strong system password. The physical console can still use opensonix/opensonix
# as a local recovery path before onboarding.
mkdir -p "${ROOTFS_DIR}/etc/ssh/sshd_config.d"
rm -f "${ROOTFS_DIR}/etc/ssh/sshd_config.d/rename_user.conf"
cat > "${ROOTFS_DIR}/etc/ssh/sshd_config.d/99-opensonix.conf" << 'SSHEOF'
PermitRootLogin no
PasswordAuthentication no
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
AllowUsers opensonix
SSHEOF

# Install authorized key for the opensonix user.
install -d -m 700 "${ROOTFS_DIR}/home/opensonix/.ssh"
install -m 600 "${STAGE_DIR}/id_ed25519.pub" "${ROOTFS_DIR}/home/opensonix/.ssh/authorized_keys"

on_chroot << 'EOF'
chown -R opensonix:opensonix /home/opensonix/.ssh
EOF
