#!/bin/bash -e

# Firmware version stamp (written by CI from the git tag)
[ -f "${STAGE_DIR}/files/opensonix-release" ] && \
    install -m 644 "${STAGE_DIR}/files/opensonix-release" "${ROOTFS_DIR}/etc/opensonix-release"

install -d "${ROOTFS_DIR}/etc/baresip"
install -m 664 "${STAGE_DIR}/files/baresip-config/config"   "${ROOTFS_DIR}/etc/baresip/config"
install -m 664 "${STAGE_DIR}/files/baresip-config/accounts" "${ROOTFS_DIR}/etc/baresip/accounts"

install -d -m 750 "${ROOTFS_DIR}/var/lib/opensonix"

on_chroot << 'EOF'
chown root:opensonix /etc/baresip /etc/baresip/config /etc/baresip/accounts
chmod 775 /etc/baresip
chmod 664 /etc/baresip/config /etc/baresip/accounts

chown -R opensonix:opensonix /opt/opensonix
chown    opensonix:opensonix /var/lib/opensonix
EOF

# ── Sudo (NOPASSWD — opensonix-ui service runs systemctl, timedatectl, etc.) ──
echo "opensonix ALL=(ALL) NOPASSWD: ALL" \
    > "${ROOTFS_DIR}/etc/sudoers.d/010_opensonix-nopasswd"
chmod 440 "${ROOTFS_DIR}/etc/sudoers.d/010_opensonix-nopasswd"

# ── Network (systemd-networkd) ────────────────────────────────────────────────
mkdir -p "${ROOTFS_DIR}/etc/systemd/network"
cat > "${ROOTFS_DIR}/etc/systemd/network/10-eth0.network" << 'NETEOF'
[Match]
Name=eth0

[Network]
DHCP=yes
NETEOF

# Point resolv.conf to systemd-resolved stub
ln -sf /run/systemd/resolve/stub-resolv.conf "${ROOTFS_DIR}/etc/resolv.conf"

# ── NTP (chrony) ──────────────────────────────────────────────────────────────
# Install default config with European NTP pool servers.
cat > "${ROOTFS_DIR}/etc/chrony/chrony.conf" << 'CHRONYEOF'
# Generated by OpenSonix — managed via web UI
server 0.europe.pool.ntp.org iburst
server 1.europe.pool.ntp.org iburst

makestep 1.0 3
driftfile /var/lib/chrony/chrony.drift
rtcsync
CHRONYEOF

# ── SSH hardening ─────────────────────────────────────────────────────────────
# Disable password auth — keys only.
mkdir -p "${ROOTFS_DIR}/etc/ssh/sshd_config.d"
cat > "${ROOTFS_DIR}/etc/ssh/sshd_config.d/99-opensonix.conf" << 'SSHEOF'
PasswordAuthentication no
ChallengeResponseAuthentication no
SSHEOF

# Install authorized key for the opensonix user.
install -d -m 700 "${ROOTFS_DIR}/home/opensonix/.ssh"
install -m 600 "${STAGE_DIR}/id_ed25519.pub" "${ROOTFS_DIR}/home/opensonix/.ssh/authorized_keys"

on_chroot << 'EOF'
chown -R opensonix:opensonix /home/opensonix/.ssh
EOF
